// Muzzle ("flash%i") and casing ejection ("eject%i") dummies of each weapon model, in model units
// (the game scales weapon models by 0.005). The server needs them to know where shots start
// (Weapon::loadModels / Weapon::shoot), so they are baked here instead of reading the DKO files.
//
// GENERATED by `npx tsx tools/gen-weapon-dummies.ts` — do not edit by hand.

export interface WeaponDummy {
  position: [number, number, number];
  /** CMatrix3x3f layout: right = [0..2], front = [3..5], up = [6..8]. */
  matrix: number[];
}

export interface WeaponDummySet {
  flashes: WeaponDummy[];
  ejects: WeaponDummy[];
}

export const weaponDummies: Record<number, WeaponDummySet> = {
  // SMG (main/models/SMG.DKO)
  0: {
    flashes: [
      { position: [33.01178, 79.57468, 49.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [
      { position: [40.80907, 22.24636, 58.36724], matrix: [0.06351, 0.99798, 0, -0.73919, 0.04704, 0.67185, 0.67049, -0.04267, 0.74069] },
    ],
  },
  // Shotgun (main/models/ShotGun.DKO)
  1: {
    flashes: [
      { position: [15.85856, 109.57468, 49.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [
      { position: [27.63066, 46.0872, 57.75343], matrix: [-0.0355, 0.99937, 0, -0.67698, -0.02405, 0.73561, 0.73514, 0.02612, 0.67741] },
    ],
  },
  // Sniper Rifle (main/models/Sniper.DKO)
  2: {
    flashes: [
      { position: [24.45065, 126.5503, 49.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [
      { position: [27.54925, 50.93557, 57.19852], matrix: [-0.09472, 0.9955, 0, -0.65084, -0.06193, 0.75668, 0.75328, 0.07167, 0.65378] },
    ],
  },
  // Dual Machine Gun (main/models/DualMachineGun.DKO)
  3: {
    flashes: [
      { position: [-44.86174, 79.57468, 50.62971], matrix: [-0.99985, 0.01745, 0, 0, 0, 1, 0.01745, 0.99985, 0] },
      { position: [44.85804, 79.57468, 49.73372], matrix: [-0.99985, -0.01745, 0, 0, 0, 1, -0.01745, 0.99985, 0] },
    ],
    ejects: [
      { position: [58.06757, 24.40182, 58.55985], matrix: [0.06497, 0.99789, 0, -0.75538, 0.04918, 0.65343, 0.65205, -0.04245, 0.75698] },
      { position: [-57.89193, 27.9515, 58.73616], matrix: [0.06346, -0.99798, 0, 0.7386, 0.04697, 0.67251, -0.67115, -0.04268, 0.74009] },
    ],
  },
  // ChainGun (main/models/ChainGun.DKO)
  4: {
    flashes: [
      { position: [60.31985, 79.57468, 49.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
      { position: [50.31985, 79.57468, 39.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
      { position: [40.31985, 79.57468, 49.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
      { position: [50.31985, 79.57468, 59.73372], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [
      { position: [58.37799, 19.47123, 57.94247], matrix: [0.06177, 0.99809, 0, -0.71804, 0.04444, 0.69458, 0.69325, -0.04291, 0.71941] },
      { position: [58.37799, 19.47123, 57.94247], matrix: [0.06177, 0.99809, 0, -0.71804, 0.04444, 0.69458, 0.69325, -0.04291, 0.71941] },
      { position: [58.37799, 19.47123, 57.94247], matrix: [0.06177, 0.99809, 0, -0.71804, 0.04444, 0.69458, 0.69325, -0.04291, 0.71941] },
      { position: [58.37799, 19.47123, 57.94247], matrix: [0.06177, 0.99809, 0, -0.71804, 0.04444, 0.69458, 0.69325, -0.04291, 0.71941] },
    ],
  },
  // Bazooka (main/models/Bazooka.DKO)
  5: {
    flashes: [
      { position: [35.16093, 80, 83.9482], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [],
  },
  // Photon Rifle (main/models/PhotonRifle.DKO)
  6: {
    flashes: [
      { position: [28.62369, 57.68626, 50.05292], matrix: [-4.35049, 0, 0, 0, 0, 4.35049, 0, 4.35049, 0] },
    ],
    ejects: [
      { position: [49.0081, 20.68284, 50.05292], matrix: [-1.48795, 4.08812, 0, 0, 0, 4.35049, 4.08812, 1.48795, 0] },
    ],
  },
  // Flame Thrower (main/models/FlameThrower.DKO)
  7: {
    flashes: [
      { position: [39.117, 69.8148, 49.70646], matrix: [-4.35049, 0, 0, 0, 0, 4.35049, 0, 4.35049, 0] },
    ],
    ejects: [
      { position: [0.44333, -57.84554, 67.0962], matrix: [4.35049, 0, 0, 0, 3.56371, 2.49534, 0, -2.49534, 3.56371] },
    ],
  },
  // Grenade (main/models/Hand.DKO)
  8: {
    flashes: [
      { position: [30.2682, 0, 43.67816], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [],
  },
  // Flame (main/models/Hand.DKO)
  9: {
    flashes: [
      { position: [30.2682, 0, 43.67816], matrix: [-1, 0, 0, 0, 0, 1, 0, 1, 0] },
    ],
    ejects: [],
  },
  // Popup Knives (main/models/Knifes.DKO)
  10: {
    flashes: [],
    ejects: [],
  },
  // Nuke Bot (main/models/Nuclear.DKO)
  11: {
    flashes: [],
    ejects: [],
  },
  // Instant Shield (main/models/Shield.DKO)
  12: {
    flashes: [],
    ejects: [],
  },
  // Mini Bot (main/models/Antena.DKO)
  13: {
    flashes: [],
    ejects: [],
  },
};
